### ISSUE TITLE
Missing feature: remote page browsing

### ISSUE THREAD

**Issue by MatjoeP** [osakared/apc-key-25-bitwig#10]
There is no way to switch to the next available remote pages. 
Maybe [switch + octave up/down] ?

**Comment by thomasjwebb** [comment]
There's no way to reassign the octave keys they don't send out midi but just change the octave. In the future it might be good to add the ability to configure the mappings since we've now used up all three of those button + shift combinations. And I'm not keen on the disable velocity feature honestly. But for now `shift + rec` cycles through the remote pages.
