### ISSUE TITLE
Questions about the nice to haves

### ISSUE THREAD

**Issue by giohappy** [osakared/apc-key-25-bitwig#12]
I just found your script and I'm going to give it a try soon. I would like to know wether the nice to haves listed in the README are just things not yet implemented (I could spend some time on them), or there are technical limits that prevent their implementation.

**Comment by thomasjwebb** [comment]
I'm sorry I didn't notice this before. Even though I tried turning on notifications for everything in github somehow I don't notice new issues sometimes.

It was more just me brainstorming, kind of a to do. Most are definitely possible within the Bitwig api. After I merge my changes in the `grig.controller` branch, I'll move any remaining missing features into issues. Although note that I basically rewrote it from the ground up so that it's no longer a javascript file. The new version will be in haxe, generating a Java/JVM-based Bitwig extension. In some ways it's more complicated to develop just because of the build environment but it'll also mean that the same code base will ultimately work in multiple different DAWs.
